version: 2.1

orbs:
  flutter: circleci/flutter@2.0.1
  android: circleci/android@2.3.0

parameters:
  app_name:
    type: string
    default: "Kannasol"
  package_name:
    type: string
    default: "com.empresa.kannasol"
  app_url:
    type: string
    default: "https://example.com"
  target_platform:
    type: string
    default: "android"
  enable_chatbot:
    type: boolean
    default: false

jobs:
  build_android:
    executor: cimg/android:2023.06
    steps:
      - checkout
      - restore_cache:
          keys:
            - flutter-pub-cache-v1-{{ checksum "pubspec.yaml" }}
            - flutter-pub-cache-v1-
      - run:
          name: Install Flutter SDK
          command: |
            if [ ! -d "$HOME/flutter" ]; then
              git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
            fi
            echo "export PATH=$HOME/flutter/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            flutter doctor
      - run:
          name: Get Flutter dependencies
          command: flutter pub get
      - save_cache:
          key: flutter-pub-cache-v1-{{ checksum "pubspec.yaml" }}
          paths:
            - ~/.pub-cache
            - $HOME/flutter
      - run:
          name: Build Android APK
          command: flutter build apk --release --target-platform android-arm64
      - run:
          name: Build Android AAB
          command: flutter build appbundle --release --target-platform android-arm64
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk
      - store_artifacts:
          path: build/app/outputs/bundle/release/app-release.aab
          destination: app-release.aab
      - store_artifacts:
          path: android/app/key.jks
          destination: keystore.jks

workflows:
  build_and_deploy:
    jobs:
      - build_android